name: ThesisProof
favicon: null
layout_spectrum: 0.5588668156415224
typography_spectrum: 0.88921
title: 'Edits that makes our work shine!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#92000a'
    - '#b9a6a2'
    - '#000000'
    - '#a65a36'
  brandStrength: 0.5625
  lightness: 0.01163468137383461
  saturation: 0.4995381112676114
  rhythmicContrast: 0.8596966320183128
purpose: []
